#!/usr/bin/env bash
# images/build.sh — build a PrepperPi SD image using pi-gen in Docker.
#
# Designed to run natively on ARM64 hosts (Apple Silicon Mac, a Pi,
# GitHub's ubuntu-24.04-arm runners) where Docker pulls the arm64
# Debian base image, no qemu emulation needed. It will also run on
# x86_64 via qemu-user-static -- just slower.
#
# Usage:
#   images/build.sh
#
# Environment overrides:
#   PI_GEN_REF        git ref of RPi-Distro/pi-gen to use (default: master)
#   PREPPERPI_WORK    local build work dir (default: images/.work)
#   PREPPERPI_OUT     local artifact dir   (default: images/out)
#
# Output:
#   images/out/prepperpi-<version>-<date>-prepperpi.img.xz
#   images/out/prepperpi-<version>-<date>-prepperpi.img.xz.sha256

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
readonly WORK_DIR="${PREPPERPI_WORK:-${SCRIPT_DIR}/.work}"
readonly OUT_DIR="${PREPPERPI_OUT:-${SCRIPT_DIR}/out}"
readonly PI_GEN_REPO="https://github.com/RPi-Distro/pi-gen"
# pi-gen's `arm64` branch produces 64-bit Pi OS Lite images for Pi 3B+
# onwards. The `master` branch is 32-bit armhf, which is NOT what we
# want (Pi 4B+ with 4 GB+ RAM benefits from arm64).
readonly PI_GEN_REF="${PI_GEN_REF:-arm64}"
readonly PI_GEN_DIR="${WORK_DIR}/pi-gen"

log() { printf '[prepperpi/image] %s\n' "$*"; }
die() { printf '[prepperpi/image] FATAL: %s\n' "$*" >&2; exit 1; }

check_docker() {
  command -v docker >/dev/null || die "docker not found in PATH"
  docker info >/dev/null 2>&1 || die "docker daemon not reachable (is Docker Desktop running?)"
  # Native arm64 containers on arm64 hosts avoid qemu. Warn (don't
  # fail) on x86_64 so contributors without arm64 still get a build.
  local host_arch
  host_arch=$(uname -m)
  case "$host_arch" in
    arm64|aarch64)
      log "host is ${host_arch}; pi-gen will build natively (fast)" ;;
    x86_64|amd64)
      log "host is ${host_arch}; pi-gen will use qemu-user-static (slow; expect 45-90 min)" ;;
    *)
      log "host arch ${host_arch} is unexpected; build may fail" ;;
  esac
}

clone_pi_gen() {
  if [[ -d "${PI_GEN_DIR}/.git" ]]; then
    local current_ref
    current_ref=$(git -C "$PI_GEN_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
    if [[ "$current_ref" == "$PI_GEN_REF" ]]; then
      log "reusing existing pi-gen clone at ${PI_GEN_DIR} (on ${PI_GEN_REF})"
      return 0
    fi
    log "existing pi-gen clone is on '${current_ref}', need '${PI_GEN_REF}'; re-cloning"
    rm -rf "$PI_GEN_DIR"
  fi
  log "cloning pi-gen (ref=${PI_GEN_REF}) to ${PI_GEN_DIR}"
  mkdir -p "$WORK_DIR"
  git clone --depth 1 --branch "$PI_GEN_REF" "$PI_GEN_REPO" "$PI_GEN_DIR"
}

stage_prepperpi() {
  local version commit
  version=$(git -C "$REPO_DIR" describe --tags --always --dirty 2>/dev/null || echo 'unknown')
  commit=$(git -C "$REPO_DIR" rev-parse HEAD 2>/dev/null || echo 'unknown')

  log "staging PrepperPi customization into pi-gen (version=${version})"

  # Copy our stage directory into pi-gen.
  rm -rf "${PI_GEN_DIR}/stage-prepperpi"
  cp -a "${SCRIPT_DIR}/stage-prepperpi" "${PI_GEN_DIR}/stage-prepperpi"

  # Copy the PrepperPi repo into pi-gen so the stage scripts can reach
  # it via the /pi-gen mount point inside the build container.
  rm -rf "${PI_GEN_DIR}/prepperpi-src"
  mkdir -p "${PI_GEN_DIR}/prepperpi-src"
  rsync -a \
    --exclude='.git' \
    --exclude='images/.work' \
    --exclude='images/out' \
    "${REPO_DIR}/" "${PI_GEN_DIR}/prepperpi-src/"

  # Generate the final pi-gen config by concatenating our template
  # with the per-build env vars (pi-gen sources this file so exports
  # survive into the stage scripts).
  {
    cat "${SCRIPT_DIR}/config"
    echo
    echo "# -- generated by images/build.sh --"
    printf 'export PREPPERPI_REPO="/pi-gen/prepperpi-src"\n'
    printf 'export PREPPERPI_VERSION="%s"\n' "$version"
    printf 'export PREPPERPI_COMMIT="%s"\n'  "$commit"
  } > "${PI_GEN_DIR}/config"

  # Skip the desktop stages (stage3, stage4, stage5) -- we only want
  # stage0-2 (lite base) + our stage. The SKIP and SKIP_IMAGES flag
  # files tell pi-gen to not bother running or exporting those.
  local s
  for s in stage3 stage4 stage5; do
    if [[ -d "${PI_GEN_DIR}/${s}" ]]; then
      touch "${PI_GEN_DIR}/${s}/SKIP" "${PI_GEN_DIR}/${s}/SKIP_IMAGES"
    fi
  done

  # Drop our pi-gen patches into the right sub-steps of pi-gen's own
  # stages. Today it's just one file that blocks apt-listchanges (see
  # the patch header for the Docker Desktop DNS rationale).
  #
  # Pi-gen's sub-stage runner ONLY executes files matching very
  # specific name conventions: `NN-run.sh` (outside chroot),
  # `NN-run-chroot.sh` (inside chroot), `NN-packages`, `NN-patches`,
  # etc. Files with other names are silently ignored. Our patch source
  # has a descriptive filename for self-documentation in this repo,
  # but we install it as `02-run.sh` so pi-gen will actually execute
  # it (after stage0/00-configure-apt's own 00-run.sh and 01-packages).
  local patch_src="${SCRIPT_DIR}/pi-gen-patches/02-no-listchanges.sh"
  local patch_dst="${PI_GEN_DIR}/stage0/00-configure-apt/02-run.sh"
  install -m 0755 "$patch_src" "$patch_dst"
  log "patched pi-gen stage0: ${patch_dst##${PI_GEN_DIR}/}"
}

run_build() {
  # Nuke any stale per-stage output from a previous (possibly failed)
  # run. pi-gen is not incremental; a partially-bootstrapped rootfs
  # left under pi-gen/work/ will confuse debootstrap on the next run
  # ("rmdir: Directory not empty") and sometimes cause it to fall back
  # to fetching Release instead of InRelease, which then fails too.
  # Set PREPPERPI_KEEP_WORK=1 to skip this cleanup during debugging.
  if [[ -d "${PI_GEN_DIR}/work" && "${PREPPERPI_KEEP_WORK:-0}" != "1" ]]; then
    log "clearing stale pi-gen work dir (set PREPPERPI_KEEP_WORK=1 to preserve)"
    rm -rf "${PI_GEN_DIR}/work"
  fi

  log "starting pi-gen build-docker.sh (this is the slow part)"
  cd "$PI_GEN_DIR"
  # build-docker.sh reads the config we wrote above and mounts the
  # pi-gen checkout at /pi-gen inside the build container.
  ./build-docker.sh
}

collect_output() {
  mkdir -p "$OUT_DIR"
  # pi-gen's arm64 branch packs its final artifact as a .zip containing
  # the raw .img (Raspberry Pi Imager reads zipped images natively), and
  # writes both a "-lite" image from stage2 and a "-prepperpi" image
  # from our stage. We want the prepperpi one -- it has the full
  # customization on top of the lite base.
  local img
  img=$(find "${PI_GEN_DIR}/deploy" -maxdepth 2 -name '*prepperpi*.zip' -type f 2>/dev/null | head -n1) || true
  if [[ -z "${img:-}" ]]; then
    # Fall back to .img.xz in case a future pi-gen version switches
    # back to that format.
    img=$(find "${PI_GEN_DIR}/deploy" -maxdepth 2 -name '*prepperpi*.img.xz' -type f 2>/dev/null | head -n1) || true
  fi
  [[ -n "${img:-}" ]] || die "no prepperpi image found under ${PI_GEN_DIR}/deploy/"

  local base
  base=$(basename "$img")
  cp "$img" "${OUT_DIR}/${base}"
  (cd "$OUT_DIR" && sha256sum "$base" > "${base}.sha256")

  log "artifact: ${OUT_DIR}/${base}"
  log "sha256:   ${OUT_DIR}/${base}.sha256"
  ls -lh "${OUT_DIR}/${base}"
}

main() {
  check_docker
  clone_pi_gen
  stage_prepperpi
  run_build
  collect_output
  log "done"
}

main "$@"
